# Generated by Django 5.0.1 on 2024-01-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactsText', models.TextField()),
                ('receiveDistributionUrl', models.URLField(max_length=255)),
                ('privacyPolicyUrl', models.URLField(max_length=255)),
                ('userAgreementUrl', models.URLField(max_length=255)),
                ('contactInformationUrl', models.URLField(max_length=255)),
                ('wideBanner', models.ImageField(upload_to='')),
                ('narrowBanner', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField(max_length=255)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitesettings')),
            ],
        ),
    ]
