# Generated by Django 5.0.1 on 2024-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_color_format_material_productform_render_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contactsText',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='addressUrl',
            field=models.URLField(default='', verbose_name='Ссылка на адрес на картах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Адрес электронной почты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='', verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='termsOfUseUrl',
            field=models.URLField(default='', max_length=255, verbose_name='Ссылка на условия использования'),
            preserve_default=False,
        ),
    ]
