# Generated by Django 5.0.1 on 2024-01-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sitesettings_contactstext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='formats',
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='3D-модель')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.format', verbose_name='Расширение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
