# Generated by Django 5.0.1 on 2024-01-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_archive_remove_product_formats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfile',
            options={'verbose_name': 'Файл продукта', 'verbose_name_plural': 'Файлы продукта'},
        ),
        migrations.AlterField(
            model_name='product',
            name='buyUrl',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка на покупку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isPopular',
            field=models.BooleanField(default=False, verbose_name='Популярная модель'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.format', verbose_name='Расширение'),
            preserve_default=False,
        ),
    ]
