# Generated by Django 5.0.1 on 2024-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_owners_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
    ]
